#!/usr/bin/env bash

# ==============================================================================
# Use this script to build a Docker image, which will be used to run tests
# in a containerized environment.
#
# Usage:
#   ./build
# ==============================================================================

# Immediately exit from this script if any command within it returns a
# non-zero exit status (indicating an error).
#
set -e

# Build a container image from the Dockerfile in the current directory.
# Name the image "json-schema".
#
docker build -t json-schema .
