#!/usr/bin/env bash

# ==============================================================================
# Use this script to clean-up any built Docker images.
#
# Usage:
#   ./cleanup
# ==============================================================================

# Immediately exit from this script if any command within it returns a
# non-zero exit status (indicating an error).
#
set -e

# Remove any images named "json-schema".
#
docker image rm json-schema
