= JSON Schema

This repository contains a collection of common JSON Schema type definitions.

image:https://img.shields.io/github/actions/workflow/status/kieranpotts/json-schema/run-tests.yaml?branch=dev&style=flat-square&label=tests&labelColor=%23333333&color=%23008800[Tests passing]
image:https://img.shields.io/github/issues/kieranpotts/json-schema?style=flat-square&labelColor=%23333333&color=%23BB2200[Open issues]
image:https://img.shields.io/github/issues-pr/kieranpotts/json-schema?style=flat-square&labelColor=%23333333&color=%232266EE[Pull requests]

== Schemas

The following schemas are available:

* link:./doc/address.adoc[Address]
* link:./doc/country-code.adoc[Country code]
* link:./doc/currency-code.adoc[Currency code]
* link:./doc/date-time.adoc[Date and time]
* link:./doc/date-year-month.adoc[Date (year and month only)]
* link:./doc/date.adoc[Date (no time)]
* link:./doc/duration.adoc[Duration]
* link:./doc/email-address.adoc[Email address]
* link:./doc/geocoordinates.adoc[Geocoordinates]
* link:./doc/json-patch-item.adoc[JSON Patch item]
* link:./doc/json-web-encryption-token.adoc[JSON Web Encryption (JWE) token]
* link:./doc/json-web-signature-token.adoc[JSON Web Signature (JWS) token]
* link:./doc/language-code.adoc[Language code]
* link:./doc/locale.adoc[Locale]
* link:./doc/monetary-amount.adoc[Monetary amount]
* link:./doc/payment-card-expiration-date.adoc[Payment card expiration date]
* link:./doc/percentage.adoc[Percentage]
* link:./doc/person-name.adoc[Person name]
* link:./doc/province.adoc[Province]
* link:./doc/telephone-number.adoc[Telephone number]
* link:./doc/telephone-type.adoc[Telephone type]
* link:./doc/time.adoc[Time (no date)]
* link:./doc/timezone.adoc[Timezone]
* link:./doc/uuid.adoc[UUID]

== Testing

Tests can be run in a containerized environment. The only requirement is that you have *Docker* installed and running on your system. All other dependencies will be installed in the container.

First, make sure the `run` script, in the root directory of this repository, is executable:

----
chmod +x run
----

To run the tests, run the following command from the root directory of this repository:

----
./run test
----

== Acknowledgements

* https://github.com/levid-gc/paypal-api-standards/tree/master/v1/schema/json/draft-04[PayPal JSON Schema]

''''

Copyright © 2020-present Kieran Potts, link:./LICENSE.txt[MIT license]
