= Address

****
Schema: link:../src/address.schema.json[address.schema.json]
****

This schema defines an address structure with medium-grained fields and a fairly generic nomenclature. For example, `admin_area_level_1` may be used interchangeably for state, province, county, or prefecture (which are locale-specific terms).

This schema is based on PayPal's"portable address" schema, which is designed to support addresses in any country, and to be backwards compatible with http://microformats.org/wiki/adr[the address hcard microformat], forwards compatible with Google's open source https://github.com/googlei18n/libaddressinput/wiki/AddressValidationMetadata[address validation metadata] and the W3C's https://www.w3.org/TR/html51/sec-forms.html#autofill-field[HTML5.1 autofill fields], and to allow for easy mapping to and from other common address schema.

There are three parts to this address schema:

* *Street address*: Composed of `address_line_1` through `address_line_3`. This would be filled in with items such as street address, apartment number, building information, or additional guidance.

* *Administrative area*: Composed of `admin_area_1` through `admin_area_4`. This would be composed of province, city, suburb information, as needed for each country. These are presented in reverse order in this schema, as in most Western address formats in which administrative areas are presented from the smallest (`admin_area_4`) to the largest (`admin_area_1`). The nomenclature mirrors that from the HTML5.1 autofill fields specification, which is designed to be universal and to support the multi-level regional segmentation needed for countries like Brazil, China, India, Indonesia, and many other places.

* *Address details*: Needed for specific applications that need non-portable, but detailed normalized information for risk, compliance, or other scenarios.

The following provides more detailed guidance on how each field in the address schema SHOULD be used:

* `address_line_1`: Line 1 of the address, eg. number, street, etc. Example: "173 Drury Lane". This is usually a required field, for compliance and risk checks.

* `address_line_2`: Optional line 2 of the address, eg. suite, apt #, etc.

* `address_line_3`: Optional line 3 of the address, if needed. May be mapped to "Street Complement" for Brazil, and "Directions" text such as "next to {landmark}" widely used in India.

* `admin_area_4`: This may be a neighborhood, ward, or district. Smaller than `admin_area_3` (sub-locality). This may be mapped to "Postal Sorting Code" for Guernsey and many French territories such as French Guiana, for the fine-grained administrative levels in China.

* `admin_area_3`: Usually used for sub-locality, suburb, neighbourhood, or district. Smaller than `admin_area_2` This could be a suburb, or "Bairro/Neighborhood" in Brazil. In India, street name information is often not available, but this can be replaced by the sub-locality/district whcih can be a very small area.

* `admin_area_2`: Usually city, town, or village. Smaller than `admin_area_1`.

* `admin_area_1`: This is the highest level of sub-division within a country. It usually corresponds to "Province", "State", or ISO-3166-2 subdivision. This will be a county in the UK, state in the USA, province in Canada, prefecture in Japan, and kanton in Switzerland. This is expected to be in the form that would appear in addresses formatted for delivery, eg. "CA" rather than "California".

* `postal_code`: Postal code, ZIP code, CEP, etc.

* `country_code`: The two-letter ISO territory code, as specified by the *Country Code* common type (see below). This is the only required field.

A simple United States address such as…

----
2211 North First Street
Building 17, 17.2.237
San Jose, CA 95131
----

… would be represented as…

[source,json]
----
{
  "address_line_1": "2211 North First Street",
  "address_line_2": "Building 17, 17.2.237",
  "admin_area_2": "San Jose",
  "admin_area_1": "CA",
  "postal_code": "95131",
  "country_code": "US"
}
----

And from Brazil, where you need a _neighborhood_ within a city (in this example, Bela Vista)…

----
Av. Paulista, 1098, 1º andar, apto. 101
Bela Vista
São Paulo - SP
Brasil
01310-000
----

… would be represented as…

[source,json]
----
{
  "address_line_1": "Av. Paulista, 1098",
  "address_line_2": "1º andar, apto. 101",
  "admin_area_3": "Bela Vista",
  "admin_area_2": "São Paulo",
  "admin_area_1": "SP",
  "postal_code": "01310-000",
  "country_code": "BR"
}
----

== Address details

Some applications need additional detail such as for risk and compliance, and need very specific address details for some countries. For example, there are many applications that require detailed street address or building information, or other details that are not part of an official address but are supplementary to it.

To allow for entry of additional address details, the address schema includes an optional `address_details` object. It has the following fields:

* `street_number`: Street number, eg. "173" from "173 Drury Lane".

* `street_name`: Street name. Just "Drury" from "173 Drury Lane". If the street type is not available, then this could contain both the street name and its type, as in "Drury Lane".

* `street_type`: Examples: "Lane", "Street", "Road", "Court", "Boulevard", etc.

* `delivery_service`: Post office box number, bag number, post office name, etc.

* `building_name`: Building name or number, or other premise description. Example: "Craven House". Named location, usually a building or collection of buildings with a common name.

* `sub_building`: Sub-premise. First-order entity below a named building or location, usually a singular building within a collection of buildings with a common name, or could be a flat, storey, floor, room and/or apartment.

These fields are not part of the core address schema, and indeed much of the data entered into the `address_details` section is expected to be redundant, duplicating data from the core address fields. For example, `address_line_1` is usually a combination of `address_details.street_number` + `address_details.street_name` + `address_details.street_type`.

Examples:

[source,json]
----
{
  "address_line_1": "2211 North First Street",
  "address_line_2": "Building 17, 17.2.237",
  "admin_area_2": "San Jose",
  "admin_area_1": "CA",
  "postal_code": "95131",
  "country_code": "US",
  "address_details": {
    "street_number": "2211",
    "street_name": "North First",
    "street_type": "Street"
  }
}
----

[source,json]
----
{
  "address_line_1": "Av. Paulista, 1098",
  "address_line_2": "1º andar, apto. 101",
  "admin_area_3": "Bela Vista",
  "admin_area_2": "São Paulo",
  "admin_area_1": "SP",
  "postal_code": "01310-000",
  "country_code": "BR",
  "address_details": {
    "street_number": "1098",
    "street_name": "Paulista",
    "street_type": "Avenida",
    "building_name": "",
    "sub_building": "1º andar, apto. 101"
  }
}
----

The `address_details` data is not intended to be portable to other address schema such as http://microformats.org/wiki/adr[the address hcard microformat] or the W3C's https://www.w3.org/TR/html51/sec-forms.html#autofill-field[HTML5.1 autofill fields]. However, this data can be derived from address verification and normalization services such as https://www.informatica.com/products/data-quality/data-as-a-service.html[Informatica's "AddressDoctor"].

== Usage with address validation services

This address schema can be used to *validate* that an address is provided in a valid format, but it cannot be used to *verify* that the address actually exists. To verify an address, the data needs to be mapped to another schema that can be fed into an address verification service.

The schema easily maps to Google's open source https://github.com/googlei18n/libaddressinput/wiki/AddressValidationMetadata[address validation metadata]. For required fields, the address validation metadata specifies the following codes:

* *A*: Street address array, at least one line must have data.
* *S*: State/province, usually `admin_area_1` in the address schema and HTML5.1 autocomplete fields.
* *C*: City/Locality, usually `admin_area_2` in the address schema and HTML5.1 autocomplete fields.
* *D*: District/suburb/neighborhood, usually `admin_area_3` in the address schema and HTML5.1.
* *X*: Sort code, usually `admin_area_4` in the address schema.
* *Z*: ZIP/Postal code.

For example, the Google https://www.gstatic.com/chrome/autofill/libaddressinput/chromium-i18n/ssl-address/data/US[address validation metadata for the US] has the following entry.

[source,json]
----
{
  "require": "ACSZ"
}
----

This tells us that at least `A` (`address_line_1`) plus `C` (`admin_area_2`), `S` (`admin_area_1`), and `Z` (`postal_code`) are all required fields for the US.

For Singapore, the required fields are represented by the string "AZ", which tells us that only `address_line_1` and `postal_code` are required.
